export default data = [
  {
    state: "Alabama",
    population: "4,903,185",
    electoral: 9,
    result: "R",
  },
  {
    state: "Alaska",
    population: "731,545",
    electoral: 3,
    result: "R",
  },
  {
    state: "Arizona",
    population: "7,278,717",
    electoral: 11,
    result: "B",
  },
  {
    state: "Arkansas",
    population: "3,017,804",
    electoral: 6,
    result: "R",
  },
  {
    state: "California",
    population: "39,512,223",
    electoral: 55,
    result: "B",
  },
  {
    state: "Colorado",
    population: "5,758,736",
    electoral: 9,
    result: "B",
  },
  {
    state: "Connecticut",
    population: "3,565,287",
    electoral: 7,
    result: "B",
  },
  {
    state: "Delaware",
    population: "973,764",
    electoral: 3,
    result: "B",
  },
  {
    state: "District of Columbia",
    population: "705,749",
    electoral: 3,
    result: "B",
  },
  {
    state: "Florida",
    population: "21,477,737",
    electoral: 29,
    result: "R",
  },
  {
    state: "Georgia",
    population: "10,617,423",
    electoral: 16,
    result: "B",
  },
  {
    state: "Hawaii",
    population: "1,415,872",
    electoral: 4,
    result: "B",
  },
  {
    state: "Idaho",
    population: "1,787,065",
    electoral: 4,
    result: "R",
  },
  {
    state: "Illinois",
    population: "12,671,821",
    electoral: 20,
    result: "B",
  },
  {
    state: "Indiana",
    population: "6,732,219",
    electoral: 11,
    result: "R",
  },
  {
    state: "Iowa",
    population: "3,155,070",
    electoral: 6,
    result: "R",
  },
  {
    state: "Kansas",
    population: "2,913,314",
    electoral: 6,
    result: "R",
  },
  {
    state: "Kentucky",
    population: "4,467,673",
    electoral: 8,
    result: "R",
  },
  {
    state: "Louisiana",
    population: "4,648,794",
    electoral: 8,
    result: "R",
  },
  {
    state: "Maine",
    population: "1,344,212",
    electoral: 4,
    result: "B",
  },
  {
    state: "Maryland",
    population: "6,045,680",
    electoral: 10,
    result: "B",
  },
  {
    state: "Massachusetts",
    population: "6,892,503",
    electoral: 11,
    result: "B",
  },
  {
    state: "Michigan",
    population: "9,986,857",
    electoral: 16,
    result: "B",
  },
  {
    state: "Minnesota",
    population: "5,639,632",
    electoral: 10,
    result: "B",
  },
  {
    state: "Mississippi",
    population: "2,976,149",
    electoral: 6,
    result: "R",
  },
  {
    state: "Missouri",
    population: "6,137,428",
    electoral: 10,
    result: "R",
  },
  {
    state: "Montana",
    population: "1,068,778",
    electoral: 3,
    result: "R",
  },
  {
    state: "Nebraska",
    population: "1,934,408",
    electoral: 5,
    result: "R",
  },
  {
    state: "Nevada",
    population: "3,080,156",
    electoral: 6,
    result: "B",
  },
  {
    state: "New Hampshire",
    population: "1,359,711",
    electoral: 4,
    result: "B",
  },
  {
    state: "New Jersey",
    population: "8,882,190",
    electoral: 14,
    result: "B",
  },
  {
    state: "New Mexico",
    population: "2,096,829",
    electoral: 5,
    result: "B",
  },
  {
    state: "New York",
    population: "19,453,561",
    electoral: 29,
    result: "B",
  },
  {
    state: "North Carolina",
    population: "10,488,084",
    electoral: 15,
    result: "R",
  },
  {
    state: "North Dakota",
    population: "762,062",
    electoral: 3,
    result: "R",
  },
  {
    state: "Ohio",
    population: "11,689,100",
    electoral: 18,
    result: "R",
  },
  {
    state: "Oklahoma",
    population: "3,956,971",
    electoral: 7,
    result: "R",
  },
  {
    state: "Oregon",
    population: "4,217,737",
    electoral: 7,
    result: "R",
  },
  {
    state: "Pennsylvania",
    population: "12,801,989",
    electoral: 20,
    result: "B",
  },
  {
    state: "Rhode Island",
    population: "1,059,361",
    electoral: 4,
    result: "B",
  },
  {
    state: "South Carolina",
    population: "5,148,714",
    electoral: 9,
    result: "R",
  },
  {
    state: "South Dakota",
    population: "884,659",
    electoral: 3,
    result: "R",
  },
  {
    state: "Tennessee",
    population: "6,829,174",
    electoral: 11,
    result: "R",
  },
  {
    state: "Texas",
    population: "28,995,881",
    electoral: 38,
    result: "R",
  },
  {
    state: "Utah",
    population: "3,205,958",
    electoral: 6,
    result: "R",
  },
  {
    state: "Vermont",
    population: "623,989",
    electoral: 3,
    result: "B",
  },
  {
    state: "Virginia",
    population: "8,535,519",
    electoral: 13,
    result: "B",
  },
  {
    state: "Washington",
    population: "7,614,893",
    electoral: 12,
    result: "B",
  },
  {
    state: "West Virginia",
    population: "1,792,147",
    electoral: 5,
    result: "R",
  },
  {
    state: "Wisconsin",
    population: "5,822,434",
    electoral: 10,
    result: "B",
  },
  {
    state: "Wyoming",
    population: "578,759",
    electoral: 3,
    result: "R",
  },
];
