const data = [
  {
    state: "Alabama",
    population: 4903185,
    electoral: 9,
    result: "Trump",
  },
  {
    state: "Alaska",
    population: 731545,
    electoral: 3,
    result: "Trump",
  },
  {
    state: "Arizona",
    population: 7278717,
    electoral: 11,
    result: "Biden",
  },
  {
    state: "Arkansas",
    population: 3017804,
    electoral: 6,
    result: "Trump",
  },
  {
    state: "California",
    population: 39512223,
    electoral: 55,
    result: "Biden",
  },
  {
    state: "Colorado",
    population: 5758736,
    electoral: 9,
    result: "Biden",
  },
  {
    state: "Connecticut",
    population: 3565287,
    electoral: 7,
    result: "Biden",
  },
  {
    state: "Delaware",
    population: 973764,
    electoral: 3,
    result: "Biden",
  },
  {
    state: "District of Columbia",
    population: 705749,
    electoral: 3,
    result: "Biden",
  },
  {
    state: "Florida",
    population: 21477737,
    electoral: 29,
    result: "Trump",
  },
  {
    state: "Georgia",
    population: 10617423,
    electoral: 16,
    result: "Biden",
  },
  {
    state: "Hawaii",
    population: 1415872,
    electoral: 4,
    result: "Biden",
  },
  {
    state: "Idaho",
    population: 1787065,
    electoral: 4,
    result: "Trump",
  },
  {
    state: "Illinois",
    population: 12671821,
    electoral: 20,
    result: "Biden",
  },
  {
    state: "Indiana",
    population: 6732219,
    electoral: 11,
    result: "Trump",
  },
  {
    state: "Iowa",
    population: 3155070,
    electoral: 6,
    result: "Trump",
  },
  {
    state: "Kansas",
    population: 2913314,
    electoral: 6,
    result: "Trump",
  },
  {
    state: "Kentucky",
    population: 4467673,
    electoral: 8,
    result: "Trump",
  },
  {
    state: "Louisiana",
    population: 4648794,
    electoral: 8,
    result: "Trump",
  },
  {
    state: "Maine",
    population: 1344212,
    electoral: 4,
    result: "Biden",
  },
  {
    state: "Maryland",
    population: 6045680,
    electoral: 10,
    result: "Biden",
  },
  {
    state: "Massachusetts",
    population: 6892503,
    electoral: 11,
    result: "Biden",
  },
  {
    state: "Michigan",
    population: 9986857,
    electoral: 16,
    result: "Biden",
  },
  {
    state: "Minnesota",
    population: 5639632,
    electoral: 10,
    result: "Biden",
  },
  {
    state: "Mississippi",
    population: 2976149,
    electoral: 6,
    result: "Trump",
  },
  {
    state: "Missouri",
    population: 6137428,
    electoral: 10,
    result: "Trump",
  },
  {
    state: "Montana",
    population: 1068778,
    electoral: 3,
    result: "Trump",
  },
  {
    state: "Nebraska",
    population: 1934408,
    electoral: 5,
    result: "Trump",
  },
  {
    state: "Nevada",
    population: 3080156,
    electoral: 6,
    result: "Biden",
  },
  {
    state: "New Hampshire",
    population: 1359711,
    electoral: 4,
    result: "Biden",
  },
  {
    state: "New Jersey",
    population: 8882190,
    electoral: 14,
    result: "Biden",
  },
  {
    state: "New Mexico",
    population: 2096829,
    electoral: 5,
    result: "Biden",
  },
  {
    state: "New York",
    population: 19453561,
    electoral: 29,
    result: "Biden",
  },
  {
    state: "North Carolina",
    population: 10488084,
    electoral: 15,
    result: "Trump",
  },
  {
    state: "North Dakota",
    population: 762062,
    electoral: 3,
    result: "Trump",
  },
  {
    state: "Ohio",
    population: 11689100,
    electoral: 18,
    result: "Trump",
  },
  {
    state: "Oklahoma",
    population: 3956971,
    electoral: 7,
    result: "Trump",
  },
  {
    state: "Oregon",
    population: 4217737,
    electoral: 7,
    result: "Biden",
  },
  {
    state: "Pennsylvania",
    population: 12801989,
    electoral: 20,
    result: "Biden",
  },
  {
    state: "Rhode Island",
    population: 1059361,
    electoral: 4,
    result: "Biden",
  },
  {
    state: "South Carolina",
    population: 5148714,
    electoral: 9,
    result: "Trump",
  },
  {
    state: "South Dakota",
    population: 884659,
    electoral: 3,
    result: "Trump",
  },
  {
    state: "Tennessee",
    population: 6829174,
    electoral: 11,
    result: "Trump",
  },
  {
    state: "Texas",
    population: 28995881,
    electoral: 38,
    result: "Trump",
  },
  {
    state: "Utah",
    population: 3205958,
    electoral: 6,
    result: "Trump",
  },
  {
    state: "Vermont",
    population: 623989,
    electoral: 3,
    result: "Biden",
  },
  {
    state: "Virginia",
    population: 8535519,
    electoral: 13,
    result: "Biden",
  },
  {
    state: "Washington",
    population: 7614893,
    electoral: 12,
    result: "Biden",
  },
  {
    state: "West Virginia",
    population: 1792147,
    electoral: 5,
    result: "Trump",
  },
  {
    state: "Wisconsin",
    population: 5822434,
    electoral: 10,
    result: "Biden",
  },
  {
    state: "Wyoming",
    population: 578759,
    electoral: 3,
    result: "Trump",
  },
];

export default data;
